/**
 * Product model
 * Source of truth: Supabase `products` table
 *
 * NOTE:
 * - Keep this model lean
 * - No UI-only or speculative fields
 * - Any future extensions must be additive
 */

export type ProductStatus = 'ACTIVE' | 'INACTIVE';

export interface Product {
    /** UUID from Supabase */
    id: string;

    /** Product display name */
    name: string;

    /** Optional long description */
    description: string | null;

    /** Price stored as numeric in DB */
    price: number;

    /** Available stock (nullable for non-inventory items) */
    stock: number | null;

    /** Business status flag */
    status: ProductStatus;

    /** Public image URLs (Supabase storage) */
    images: string[];

    /** Foreign key to categories table */
    category_id: string | null;

    /** ISO timestamp (read-only) */
    created_at: string;

    /** ISO timestamp (read-only) */
    updated_at: string;
}

/**
 * Payload used when creating a product
 * (id & timestamps are generated by backend)
 */
export type CreateProductPayload = Omit<
    Product,
    'id' | 'created_at' | 'updated_at'
>;

/**
 * Payload used when updating a product
 * (partial updates allowed)
 */
export type UpdateProductPayload = Partial<CreateProductPayload>;
